/**
 * 策略模块配置
 * 包含策略管理、策略监控等页面的配置
 */

import type { ModuleConfig } from '@btc/shared-core/types/module';
import type { TableColumn, FormItem } from '@btc/shared-components';

// 参考 cool-admin-vue-7.x 的方式：延迟导入 service，避免初始化顺序问题
let _serviceCache: any = null;

function getService() {
  if (_serviceCache) return _serviceCache;
  if (typeof window === 'undefined') {
    _serviceCache = {} as any;
    return _serviceCache;
  }
  const win = window as any;
  const globalService = win.__APP_EPS_SERVICE__ || win.__BTC_SERVICE__;
  if (globalService && typeof globalService === 'object' && Object.keys(globalService).length > 0) {
    _serviceCache = globalService;
    return _serviceCache;
  }
  if (!_serviceCache) {
    try {
      const cachedModule = (win as any).__EPS_MODULE_CACHE__;
      if (cachedModule) {
        _serviceCache = cachedModule.service || cachedModule.default || {};
        return _serviceCache;
      }
    } catch (error) {}
  }
  _serviceCache = _serviceCache || {} as any;
  return _serviceCache;
}

export default {
  // ModuleConfig 字段
  name: 'strategy',
  label: 'common.module.strategy.label',
  order: 45,

  // 路由配置
  views: [
    {
      path: '/strategy/management',
      name: 'AdminStrategyManagement',
      component: () => import('./views/management/index.vue'),
      meta: {
        isPage: true,
        titleKey: 'menu.strategy.management',
      },
    },
    {
      path: '/strategy/designer',
      name: 'AdminStrategyDesigner',
      component: () => import('./views/designer/index.vue'),
      meta: {
        isPage: true,
        titleKey: 'menu.strategy.designer',
      },
    },
    {
      path: '/strategy/monitor',
      name: 'AdminStrategyMonitor',
      component: () => import('./views/monitor/index.vue'),
      meta: {
        isPage: true,
        titleKey: 'menu.strategy.monitor',
      },
    },
  ],

  // PageConfig 字段（保留）
  // 国际化配置（扁平结构）
  locale: {
    'zh-CN': {
      // 菜单配置
      'menu.strategy': '策略中心',
      'menu.strategy.management': '策略管理',
      'menu.strategy.designer': '策略编排',
      'menu.strategy.monitor': '策略监控',
      // 策略管理相关
      'strategy.management.fields.strategy_name': '策略名称',
      'strategy.management.fields.strategy_code': '策略编码',
      'strategy.management.fields.type': '类型',
      'strategy.management.fields.version': '版本',
      'strategy.management.fields.status': '状态',
      'strategy.management.fields.priority': '优先级',
      'strategy.management.fields.tags': '标签',
      'strategy.management.fields.description': '描述',
      'strategy.management.fields.created_at': '创建时间',
      'strategy.management.fields.updated_at': '更新时间',
      'strategy.management.types.permission': '权限策略',
      'strategy.management.types.business': '业务策略',
      'strategy.management.types.data': '数据策略',
      'strategy.management.types.workflow': '工作流策略',
      'strategy.management.status.draft': '草稿',
      'strategy.management.status.testing': '测试中',
      'strategy.management.status.active': '激活',
      'strategy.management.status.inactive': '停用',
      'strategy.management.status.archived': '已归档',
      'strategy.management.tags_placeholder': '多个标签用逗号分隔',
      'strategy.management.version_history': '版本历史',
      'strategy.management.version': '版本',
      'strategy.management.updated_at': '更新时间',
      'strategy.management.updated_by': '更新人',
      'strategy.management.activate': '激活',
      'strategy.management.compare': '对比',
      'strategy.management.test': '策略测试',
      'strategy.management.test_context': '测试上下文',
      'strategy.management.test_context_placeholder': '请输入JSON格式的测试上下文',
      'strategy.management.test_result': '测试结果',
      'strategy.management.execution_result': '执行结果',
      'strategy.management.strategy_effect': '策略效果',
      'strategy.management.execution_time': '执行时间',
      'strategy.management.execution_steps': '执行步骤',
      'strategy.management.success': '成功',
      'strategy.management.failed': '失败',
      'strategy.management.version_activate_success': '版本激活成功',
      'strategy.management.version_activate_failed': '版本激活失败',
      'strategy.management.version_compare_coming_soon': '版本对比功能将在后续版本实现',
      'strategy.management.get_version_history_failed': '获取版本历史失败',
      'strategy.management.status_filter': '状态筛选',
      'strategy.management.execution_steps_detail': '执行步骤详情',
      'strategy.management.execute_test': '执行测试',
      'strategy.management.test_complete': '策略测试完成',
      'strategy.management.test_failed': '策略测试失败',
      'strategy.management.result': '结果',
      'strategy.management.error': '错误',
      // 策略编排相关
      'strategy.designer.basic_properties': '基础属性',
      'strategy.designer.node_name': '节点名称',
      'strategy.designer.node_description': '节点描述',
      'strategy.designer.node_type': '节点类型',
      'strategy.designer.style_properties': '样式属性',
      'strategy.designer.width': '宽度',
      'strategy.designer.height': '高度',
      'strategy.designer.background_color': '背景颜色',
      'strategy.designer.border_color': '边框颜色',
      'strategy.designer.node_config': '节点配置',
      'strategy.designer.enter_node_name': '请输入节点名称',
      'strategy.designer.enter_node_description': '请输入节点描述',
      'strategy.designer.enter_color_value': '请输入颜色值，例如 #ff0000',
      'strategy.designer.select_node_or_connection': '请选择节点或连接',
      'strategy.designer.invalid_file_format': '无效的编排文件格式',
      'strategy.designer.file_read_failed': '文件读取失败',
      'strategy.designer.gateway_config': '网关配置',
      'strategy.designer.gateway_type': '网关类型',
      'strategy.designer.gateway_types.parallel': '并行网关',
      'strategy.designer.gateway_types.exclusive': '排他网关',
      'strategy.designer.gateway_types.inclusive': '包容网关',
      'strategy.designer.gateway_types.complex': '复杂网关',
      'strategy.designer.merge_strategy': '合并策略',
      'strategy.designer.merge_strategy_all': '全部通过',
      'strategy.designer.merge_strategy_any': '任意通过',
      'strategy.designer.merge_strategy_majority': '多数通过',
      'strategy.designer.merge_strategy_custom': '自定义',
      'strategy.designer.custom_rule': '自定义规则',
      'strategy.designer.custom_rule_placeholder': '例如 (result1 且 result2) 或 result3',
      'strategy.designer.timeout': '超时',
      'strategy.designer.milliseconds': '毫秒',
      'strategy.designer.parallel_execution': '并行执行',
      'strategy.designer.failure_handling': '失败处理',
      'strategy.designer.failure_handling_continue': '继续',
      'strategy.designer.failure_handling_stop': '停止',
      'strategy.designer.failure_handling_retry': '重试',
      'strategy.designer.retry_count': '重试次数',
      'strategy.designer.config_preview': '配置预览',
      'strategy.designer.action_types.allow_access': '允许访问',
      'strategy.designer.action_types.deny_access': '拒绝访问',
      'strategy.designer.action_types.log_event': '记录事件',
      'strategy.designer.action_types.send_notification': '发送通知',
      'strategy.designer.action_types.update_data': '更新数据',
      'strategy.designer.action_types.call_api': '调用API',
      'strategy.designer.action_types.execute_script': '执行脚本',
      'strategy.designer.action_types.set_variable': '设置变量',
      'strategy.designer.invalid_json_format': '无效的参数格式，请输入有效的JSON',
      'strategy.designer.operators.eq': '等于 (=)',
      'strategy.designer.operators.ne': '不等于 (≠)',
      'strategy.designer.operators.gt': '大于 (>)',
      'strategy.designer.operators.gte': '大于等于 (≥)',
      'strategy.designer.operators.lt': '小于 (<)',
      'strategy.designer.operators.lte': '小于等于 (≤)',
      'strategy.designer.operators.in': '包含于',
      'strategy.designer.operators.nin': '不包含于',
      'strategy.designer.operators.contains': '包含',
      'strategy.designer.operators.startsWith': '以...开始',
      'strategy.designer.operators.endsWith': '以...结束',
      'strategy.designer.operators.regex': '正则匹配',
      'strategy.designer.operators.exists': '存在',
      'strategy.designer.operators.notExists': '不存在',
      'strategy.designer.node_types.start': '开始',
      'strategy.designer.node_types.end': '结束',
      'strategy.designer.node_types.condition': '条件',
      'strategy.designer.node_types.action': '操作',
      'strategy.designer.node_types.decision': '决策',
      'strategy.designer.node_types.gateway': '网关',
      'strategy.designer.node_types.node': '节点',
      'strategy.designer.font_family.system_default': '系统默认',
      'strategy.designer.font_family.monospace': '等宽字体',
      'strategy.designer.font_family.serif': '衬线字体',
      'strategy.designer.font_family.rounded': '圆体',
      'strategy.designer.font_family.bold': '粗体',
      'strategy.designer.font_weight.thin': '细',
      'strategy.designer.font_weight.extra_light': '超细',
      'strategy.designer.font_weight.light': '细',
      'strategy.designer.font_weight.normal': '正常',
      'strategy.designer.font_weight.medium': '中等',
      'strategy.designer.font_weight.bold': '粗',
      'strategy.designer.font_style.normal': '正常',
      'strategy.designer.font_style.italic': '斜体',
      'strategy.designer.font_style.oblique': '倾斜',
      'strategy.designer.execution_preview.reset': '预览重置',
      'strategy.designer.execution_preview.add_nodes_first': '请先添加节点',
      'strategy.designer.execution_preview.invalid_input_json': '输入数据格式错误，请输入有效的JSON',
      'strategy.designer.execution_preview.start_execution': '开始策略编排',
      'strategy.designer.execution_preview.start_node_not_found': '未找到开始节点',
      'strategy.designer.execution_preview.execution_completed': '策略执行完成',
      'strategy.designer.execution_preview.execution_failed': '策略执行失败',
      'strategy.designer.execution_preview.start_executing_node': '开始执行节点',
      'strategy.designer.execution_preview.node_execution_success': '执行成功',
      'strategy.designer.execution_preview.node_execution_failed': '执行失败',
      'strategy.designer.execution_preview.component_loaded': '预览组件已加载',
      'strategy.designer.test_data_invalid_json': '测试数据格式错误，请输入有效的JSON',
      'strategy.designer.variable_invalid_json': '变量格式错误，请输入有效的JSON',
      'strategy.designer.canvas_element_not_found': '画布元素未找到',
      'strategy.designer.component_library.basic': '基础组件',
      'strategy.designer.component_library.advanced': '高级组件',
      'strategy.designer.directions.top': '上',
      'strategy.designer.directions.right': '右',
      'strategy.designer.directions.bottom': '下',
      'strategy.designer.directions.left': '左',
      'strategy.designer.node_management.only_one_start_node': '策略中只允许一个开始节点',
      'strategy.designer.node_management.only_one_end_node': '策略中只允许一个结束节点',
      'strategy.designer.node_management.delete_confirm': '确定要删除这个节点吗？',
      'strategy.designer.node_management.delete_success': '节点删除成功',
      'strategy.designer.operations.new_orchestration': '新建策略编排',
      'strategy.designer.operations.validation_passed': '策略编排验证通过',
      'strategy.designer.operations.validation_failed_prefix': '验证失败：',
      'strategy.designer.operations.validation_failed': '验证失败',
      'strategy.designer.operations.select_or_create_strategy_first': '请先选择或创建策略',
      'strategy.designer.operations.save_success': '策略编排保存成功',
      'strategy.designer.operations.load_success': '策略编排加载成功',
      'strategy.designer.operations.load_failed': '加载策略编排失败',
      'strategy.designer.operations.clear_success': '编排已清空',
      'strategy.designer.operations.export_success': '编排导出成功',
      'strategy.designer.operations.import_success': '编排导入成功',
      'strategy.designer.operations.invalid_file_format': '无效的编排文件格式',
      'strategy.designer.operations.parse_failed': '解析编排文件失败',
      'strategy.designer.operations.file_read_failed': '文件读取失败',
      'strategy.designer.strategy_name_placeholder': '策略名称',
      // 策略监控相关
      'strategy.monitor.alert_subject': '策略监控告警',
      'strategy.monitor.please_input_alert_name': '请输入告警名称',
      'strategy.monitor.please_select_alert_type': '请选择告警类型',
      'strategy.monitor.metrics.avg_response_time': '平均响应时间',
      'strategy.monitor.metrics.p95_response_time': 'P95响应时间',
      'strategy.monitor.metrics.p99_response_time': 'P99响应时间',
      'strategy.monitor.metrics.error_rate': '错误率',
      'strategy.monitor.metrics.failure_count': '失败次数',
      'strategy.monitor.metrics.execution_count': '执行次数',
      'strategy.monitor.metrics.execution_rate': '执行频率',
      'strategy.monitor.units.times': '次',
      'strategy.monitor.units.times_per_minute': '次/分钟',
      'strategy.monitor.types.performance': '性能',
      'strategy.monitor.types.error_rate': '错误率',
      'strategy.monitor.types.execution_count': '执行次数',
      'strategy.monitor.operators.gt': '大于',
      'strategy.monitor.operators.gte': '大于等于',
      'strategy.monitor.operators.lt': '小于',
      'strategy.monitor.operators.lte': '小于等于',
      'strategy.monitor.operators.eq': '等于',
      'strategy.monitor.alert_rule_preview': '告警规则预览',
      'strategy.monitor.alert_rule': '告警规则',
      'strategy.monitor.please_complete_alert_config': '请完善告警配置',
      'strategy.monitor.alert_rule_description': '当 {metric} {operator} {threshold}{unit} 且持续 {duration} 秒时触发告警',
      'strategy.monitor.alert_save_success': '告警规则保存成功',
      'strategy.monitor.delete_alert_confirm': '确定要删除这个告警规则吗？',
      'strategy.monitor.alert_delete_success': '告警规则删除成功',
      'strategy.monitor.enter_alert_name': 'Please enter alert name',
      'strategy.monitor.select_alert_type': 'Please select alert type',
      'strategy.monitor.no_error_info': 'No error information',
      'strategy.monitor.fields.strategy_name': '策略名称',
      'strategy.monitor.fields.strategy_code': '策略编码',
      'strategy.monitor.fields.type': '类型',
      'strategy.monitor.fields.status': '状态',
      'strategy.monitor.fields.priority': '优先级',
      'strategy.monitor.fields.version': '版本',
      'strategy.monitor.fields.description': '描述',
      'strategy.monitor.fields.execution_count': '执行次数',
      'strategy.monitor.fields.success_count': '成功次数',
      'strategy.monitor.fields.failure_count': '失败次数',
      'strategy.monitor.fields.last_execution_time': '最后执行时间',
      'strategy.monitor.fields.updated_at': '更新时间',
      // 策略类型和状态
      'strategy.types.permission': '权限策略',
      'strategy.types.business': '业务策略',
      'strategy.types.data': '数据策略',
      'strategy.types.workflow': '工作流策略',
      'strategy.status.draft': '草稿',
      'strategy.status.testing': '测试中',
      'strategy.status.active': '激活',
      'strategy.status.inactive': '停用',
      'strategy.status.archived': '已归档',
      // common.strategy 模块级提示信息
      'common.strategy.types.permission': '权限策略',
      'common.strategy.types.business': '业务策略',
      'common.strategy.types.data': '数据策略',
      'common.strategy.types.workflow': '工作流策略',
      'common.strategy.status.draft': '草稿',
      'common.strategy.status.testing': '测试中',
      'common.strategy.status.active': '激活',
      'common.strategy.status.inactive': '停用',
      'common.strategy.status.archived': '已归档',
      'common.strategy.management.status_filter': '状态筛选',
      'common.strategy.management.version_history': '版本历史',
      'common.strategy.management.version': '版本',
      'common.strategy.management.status': '状态',
      'common.strategy.management.updated_at': '更新时间',
      'common.strategy.management.updated_by': '更新人',
      'common.strategy.management.activate': '激活',
      'common.strategy.management.compare': '对比',
      'common.strategy.management.test': '策略测试',
      'common.strategy.management.test_context': '测试上下文',
      'common.strategy.management.test_context_placeholder': '请输入JSON格式的测试上下文',
      'common.strategy.management.test_result': '测试结果',
      'common.strategy.management.execution_result': '执行结果',
      'common.strategy.management.strategy_effect': '策略效果',
      'common.strategy.management.execution_time': '执行时间',
      'common.strategy.management.execution_steps': '执行步骤',
      'common.strategy.management.success': '成功',
      'common.strategy.management.failed': '失败',
      'common.strategy.management.execution_steps_detail': '执行步骤详情',
      'common.strategy.management.execute_test': '执行测试',
      'common.strategy.management.test_complete': '策略测试完成',
      'common.strategy.management.test_failed': '策略测试失败',
      'common.strategy.management.result': '结果',
      'common.strategy.management.error': '错误',
      'common.strategy.management.version_activate_success': '版本激活成功',
      'common.strategy.management.version_activate_failed': '版本激活失败',
      'common.strategy.management.get_version_history_failed': '获取版本历史失败',
      'common.strategy.management.clone_success': '策略克隆成功',
      'common.strategy.management.clone_failed': '策略克隆失败',
      'common.strategy.management.copy_suffix': '副本',
      'common.strategy.management.export_success': '策略导出成功',
      'common.strategy.management.export_failed': '策略导出失败',
      'common.strategy.monitor.load_execution_history_failed': '加载执行历史失败',
      'common.strategy.monitor.execution_replay_started': '执行回放已开始',
      'common.strategy.monitor.execution_replay_failed': '执行回放失败',
      'common.strategy.monitor.alert_subject': '策略监控告警',
      'common.strategy.monitor.please_input_alert_name': '请输入告警名称',
      'common.strategy.monitor.please_select_alert_type': '请选择告警类型',
      'common.strategy.monitor.metrics.avg_response_time': '平均响应时间',
      'common.strategy.monitor.metrics.p95_response_time': 'P95响应时间',
      'common.strategy.monitor.metrics.p99_response_time': 'P99响应时间',
      'common.strategy.monitor.metrics.error_rate': '错误率',
      'common.strategy.monitor.metrics.failure_count': '失败次数',
      'common.strategy.monitor.metrics.execution_count': '执行次数',
      'common.strategy.monitor.metrics.execution_rate': '执行频率',
      'common.strategy.monitor.units.times': '次',
      'common.strategy.monitor.units.times_per_minute': '次/分钟',
      'common.strategy.monitor.types.performance': '性能',
      'common.strategy.monitor.types.error_rate': '错误率',
      'common.strategy.monitor.types.execution_count': '执行次数',
      'common.strategy.monitor.operators.gt': '大于',
      'common.strategy.monitor.operators.gte': '大于等于',
      'common.strategy.monitor.operators.lt': '小于',
      'common.strategy.monitor.operators.lte': '小于等于',
      'common.strategy.monitor.operators.eq': '等于',
      'common.strategy.monitor.alert_rule_preview': '告警规则预览',
      'common.strategy.monitor.alert_rule': '告警规则',
      'common.strategy.monitor.please_complete_alert_config': '请完善告警配置',
      'common.strategy.monitor.alert_rule_description': '当 {metric} {operator} {threshold}{unit} 且持续 {duration} 秒时触发告警',
      'common.strategy.monitor.alert_save_success': '告警规则保存成功',
      'common.strategy.monitor.delete_alert_confirm': '确定要删除这个告警规则吗？',
      'common.strategy.monitor.alert_delete_success': '告警规则删除成功',
      'common.strategy.designer.component_library.basic': '基础组件',
      'common.strategy.designer.component_library.advanced': '高级组件',
      'common.strategy.designer.node_types.start': '开始',
      'common.strategy.designer.node_types.end': '结束',
      'common.strategy.designer.node_types.condition': '条件',
      'common.strategy.designer.node_types.action': '操作',
      'common.strategy.designer.node_types.decision': '决策',
      'common.strategy.designer.node_types.gateway': '网关',
      'common.strategy.designer.node_types.node': '节点',
      'common.strategy.designer.directions.top': '上',
      'common.strategy.designer.directions.right': '右',
      'common.strategy.designer.directions.bottom': '下',
      'common.strategy.designer.directions.left': '左',
      'common.strategy.designer.node_management.only_one_start_node': '策略中只允许一个开始节点',
      'common.strategy.designer.node_management.only_one_end_node': '策略中只允许一个结束节点',
      'common.strategy.designer.node_management.delete_confirm': '确定要删除这个节点吗？',
      'common.strategy.designer.node_management.delete_success': '节点删除成功',
      'common.strategy.designer.font_family.system_default': '系统默认',
      'common.strategy.designer.font_family.monospace': '等宽字体',
      'common.strategy.designer.font_family.serif': '衬线字体',
      'common.strategy.designer.font_family.rounded': '圆体',
      'common.strategy.designer.font_family.bold': '粗体',
      'common.strategy.designer.operations.new_orchestration': '新建策略编排',
    },
    'en-US': {
      // 菜单配置
      'menu.strategy': 'Strategy Center',
      'menu.strategy.management': 'Strategy Management',
      'menu.strategy.designer': 'Strategy Designer',
      'menu.strategy.monitor': 'Strategy Monitor',
      // 策略管理相关
      'strategy.management.fields.strategy_name': 'Strategy Name',
      'strategy.management.fields.strategy_code': 'Strategy Code',
      'strategy.management.fields.type': 'Type',
      'strategy.management.fields.version': 'Version',
      'strategy.management.fields.status': 'Status',
      'strategy.management.fields.priority': 'Priority',
      'strategy.management.fields.tags': 'Tags',
      'strategy.management.fields.description': 'Description',
      'strategy.management.fields.created_at': 'Created At',
      'strategy.management.fields.updated_at': 'Updated At',
      'strategy.management.types.permission': 'Permission Strategy',
      'strategy.management.types.business': 'Business Strategy',
      'strategy.management.types.data': 'Data Strategy',
      'strategy.management.types.workflow': 'Workflow Strategy',
      'strategy.management.status.draft': 'Draft',
      'strategy.management.status.testing': 'Testing',
      'strategy.management.status.active': 'Active',
      'strategy.management.status.inactive': 'Inactive',
      'strategy.management.status.archived': 'Archived',
      'strategy.management.tags_placeholder': 'Multiple tags separated by commas',
      'strategy.management.version_history': 'Version History',
      'strategy.management.version': 'Version',
      'strategy.management.updated_at': 'Updated At',
      'strategy.management.updated_by': 'Updated By',
      'strategy.management.activate': 'Activate',
      'strategy.management.compare': 'Compare',
      'strategy.management.test': 'Strategy Test',
      'strategy.management.test_context': 'Test Context',
      'strategy.management.test_context_placeholder': 'Please enter test context in JSON format',
      'strategy.management.test_result': 'Test Result',
      'strategy.management.execution_result': 'Execution Result',
      'strategy.management.strategy_effect': 'Strategy Effect',
      'strategy.management.execution_time': 'Execution Time',
      'strategy.management.execution_steps': 'Execution Steps',
      'strategy.management.success': 'Success',
      'strategy.management.failed': 'Failed',
      'strategy.management.version_activate_success': 'Version activation successful',
      'strategy.management.version_activate_failed': 'Version activation failed',
      'strategy.management.version_compare_coming_soon': 'Version comparison feature will be implemented in future versions',
      'strategy.management.get_version_history_failed': 'Failed to get version history',
      'strategy.management.status_filter': 'Status Filter',
      'strategy.management.execution_steps_detail': 'Execution Steps Detail',
      'strategy.management.execute_test': 'Execute Test',
      'strategy.management.test_complete': 'Strategy test completed',
      'strategy.management.test_failed': 'Strategy test failed',
      'strategy.management.result': 'Result',
      'strategy.management.error': 'Error',
      // 策略编排相关
      'strategy.designer.basic_properties': 'Basic Properties',
      'strategy.designer.node_name': 'Node Name',
      'strategy.designer.node_description': 'Node Description',
      'strategy.designer.node_type': 'Node Type',
      'strategy.designer.style_properties': 'Style Properties',
      'strategy.designer.width': 'Width',
      'strategy.designer.height': 'Height',
      'strategy.designer.background_color': 'Background Color',
      'strategy.designer.border_color': 'Border Color',
      'strategy.designer.node_config': 'Node Config',
      'strategy.designer.enter_node_name': 'Please enter node name',
      'strategy.designer.enter_node_description': 'Please enter node description',
      'strategy.designer.enter_color_value': 'Please enter color value, for example #ff0000',
      'strategy.designer.select_node_or_connection': 'Please select a node or connection',
      'strategy.designer.invalid_file_format': 'Invalid orchestration file format',
      'strategy.designer.file_read_failed': 'File read failed',
      'strategy.designer.gateway_config': 'Gateway Config',
      'strategy.designer.gateway_type': 'Gateway Type',
      'strategy.designer.gateway_types.parallel': 'Parallel Gateway',
      'strategy.designer.gateway_types.exclusive': 'Exclusive Gateway',
      'strategy.designer.gateway_types.inclusive': 'Inclusive Gateway',
      'strategy.designer.gateway_types.complex': 'Complex Gateway',
      'strategy.designer.merge_strategy': 'Merge Strategy',
      'strategy.designer.merge_strategy_all': 'All Pass',
      'strategy.designer.merge_strategy_any': 'Any Pass',
      'strategy.designer.merge_strategy_majority': 'Majority Pass',
      'strategy.designer.merge_strategy_custom': 'Custom',
      'strategy.designer.custom_rule': 'Custom Rule',
      'strategy.designer.custom_rule_placeholder': 'e.g. (result1 and result2) or result3',
      'strategy.designer.timeout': 'Timeout',
      'strategy.designer.milliseconds': 'ms',
      'strategy.designer.parallel_execution': 'Parallel Execution',
      'strategy.designer.failure_handling': 'Failure Handling',
      'strategy.designer.failure_handling_continue': 'Continue',
      'strategy.designer.failure_handling_stop': 'Stop',
      'strategy.designer.failure_handling_retry': 'Retry',
      'strategy.designer.retry_count': 'Retry Count',
      'strategy.designer.config_preview': 'Config Preview',
      'strategy.designer.action_types.allow_access': 'Allow Access',
      'strategy.designer.action_types.deny_access': 'Deny Access',
      'strategy.designer.action_types.log_event': 'Log Event',
      'strategy.designer.action_types.send_notification': 'Send Notification',
      'strategy.designer.action_types.update_data': 'Update Data',
      'strategy.designer.action_types.call_api': 'Call API',
      'strategy.designer.action_types.execute_script': 'Execute Script',
      'strategy.designer.action_types.set_variable': 'Set Variable',
      'strategy.designer.invalid_json_format': 'Invalid parameter format, please enter valid JSON',
      'strategy.designer.operators.eq': 'Equal (=)',
      'strategy.designer.operators.ne': 'Not Equal (≠)',
      'strategy.designer.operators.gt': 'Greater Than (>)',
      'strategy.designer.operators.gte': 'Greater Than or Equal (≥)',
      'strategy.designer.operators.lt': 'Less Than (<)',
      'strategy.designer.operators.lte': 'Less Than or Equal (≤)',
      'strategy.designer.operators.in': 'In',
      'strategy.designer.operators.nin': 'Not In',
      'strategy.designer.operators.contains': 'Contains',
      'strategy.designer.operators.startsWith': 'Starts With',
      'strategy.designer.operators.endsWith': 'Ends With',
      'strategy.designer.operators.regex': 'Regex Match',
      'strategy.designer.operators.exists': 'Exists',
      'strategy.designer.operators.notExists': 'Not Exists',
      'strategy.designer.node_types.start': 'Start',
      'strategy.designer.node_types.end': 'End',
      'strategy.designer.node_types.condition': 'Condition',
      'strategy.designer.node_types.action': 'Action',
      'strategy.designer.node_types.decision': 'Decision',
      'strategy.designer.node_types.gateway': 'Gateway',
      'strategy.designer.node_types.node': 'Node',
      'strategy.designer.font_family.system_default': 'System Default',
      'strategy.designer.font_family.monospace': 'Monospace',
      'strategy.designer.font_family.serif': 'Serif',
      'strategy.designer.font_family.rounded': 'Rounded',
      'strategy.designer.font_family.bold': 'Bold',
      'strategy.designer.font_weight.thin': 'Thin',
      'strategy.designer.font_weight.extra_light': 'Extra Light',
      'strategy.designer.font_weight.light': 'Light',
      'strategy.designer.font_weight.normal': 'Normal',
      'strategy.designer.font_weight.medium': 'Medium',
      'strategy.designer.font_weight.bold': 'Bold',
      'strategy.designer.font_style.normal': 'Normal',
      'strategy.designer.font_style.italic': 'Italic',
      'strategy.designer.font_style.oblique': 'Oblique',
      'strategy.designer.execution_preview.reset': 'Preview reset',
      'strategy.designer.execution_preview.add_nodes_first': 'Please add nodes first',
      'strategy.designer.execution_preview.invalid_input_json': 'Invalid input data format, please enter valid JSON',
      'strategy.designer.execution_preview.start_execution': 'Start strategy orchestration',
      'strategy.designer.execution_preview.start_node_not_found': 'Start node not found',
      'strategy.designer.execution_preview.execution_completed': 'Strategy execution completed',
      'strategy.designer.execution_preview.execution_failed': 'Strategy execution failed',
      'strategy.designer.execution_preview.start_executing_node': 'Start executing node',
      'strategy.designer.execution_preview.node_execution_success': 'execution successful',
      'strategy.designer.execution_preview.node_execution_failed': 'execution failed',
      'strategy.designer.execution_preview.component_loaded': 'Preview component loaded',
      'strategy.designer.test_data_invalid_json': 'Test data format error, please enter valid JSON',
      'strategy.designer.variable_invalid_json': 'Variable format error, please enter valid JSON',
      'strategy.designer.canvas_element_not_found': 'Canvas element not found',
      'strategy.designer.component_library.basic': 'Basic Components',
      'strategy.designer.component_library.advanced': 'Advanced Components',
      'strategy.designer.directions.top': 'Top',
      'strategy.designer.directions.right': 'Right',
      'strategy.designer.directions.bottom': 'Bottom',
      'strategy.designer.directions.left': 'Left',
      'strategy.designer.node_management.only_one_start_node': 'Only one start node allowed in strategy',
      'strategy.designer.node_management.only_one_end_node': 'Only one end node allowed in strategy',
      'strategy.designer.node_management.delete_confirm': 'Are you sure to delete this node?',
      'strategy.designer.node_management.delete_success': 'Node deleted successfully',
      'strategy.designer.operations.new_orchestration': 'New Strategy Orchestration',
      'strategy.designer.operations.validation_passed': 'Strategy orchestration validation passed',
      'strategy.designer.operations.validation_failed_prefix': 'Validation failed: ',
      'strategy.designer.operations.validation_failed': 'Validation failed',
      'strategy.designer.operations.select_or_create_strategy_first': 'Please select or create a strategy first',
      'strategy.designer.operations.save_success': 'Strategy orchestration saved successfully',
      'strategy.designer.operations.load_success': 'Strategy orchestration loaded successfully',
      'strategy.designer.operations.load_failed': 'Failed to load strategy orchestration',
      'strategy.designer.operations.clear_success': 'Orchestration cleared',
      'strategy.designer.operations.export_success': 'Orchestration exported successfully',
      'strategy.designer.operations.import_success': 'Orchestration imported successfully',
      'strategy.designer.operations.invalid_file_format': 'Invalid orchestration file format',
      'strategy.designer.operations.parse_failed': 'Failed to parse orchestration file',
      'strategy.designer.operations.file_read_failed': 'Failed to read file',
      // 策略监控相关
      'strategy.monitor.alert_subject': '策略监控告警',
      'strategy.monitor.please_input_alert_name': '请输入告警名称',
      'strategy.monitor.please_select_alert_type': '请选择告警类型',
      'strategy.monitor.metrics.avg_response_time': '平均响应时间',
      'strategy.monitor.metrics.p95_response_time': 'P95响应时间',
      'strategy.monitor.metrics.p99_response_time': 'P99响应时间',
      'strategy.monitor.metrics.error_rate': '错误率',
      'strategy.monitor.metrics.failure_count': '失败次数',
      'strategy.monitor.metrics.execution_count': '执行次数',
      'strategy.monitor.metrics.execution_rate': '执行频率',
      'strategy.monitor.units.times': '次',
      'strategy.monitor.units.times_per_minute': '次/分钟',
      'strategy.monitor.types.performance': '性能',
      'strategy.monitor.types.error_rate': '错误率',
      'strategy.monitor.types.execution_count': '执行次数',
      'strategy.monitor.operators.gt': '大于',
      'strategy.monitor.operators.gte': '大于等于',
      'strategy.monitor.operators.lt': '小于',
      'strategy.monitor.operators.lte': '小于等于',
      'strategy.monitor.operators.eq': '等于',
      'strategy.monitor.alert_rule_preview': '告警规则预览',
      'strategy.monitor.alert_rule': '告警规则',
      'strategy.monitor.please_complete_alert_config': '请完善告警配置',
      'strategy.monitor.alert_rule_description': '当 {metric} {operator} {threshold}{unit} 且持续 {duration} 秒时触发告警',
      'strategy.monitor.alert_save_success': '告警规则保存成功',
      'strategy.monitor.delete_alert_confirm': '确定要删除这个告警规则吗？',
      'strategy.monitor.alert_delete_success': '告警规则删除成功',
      'strategy.monitor.enter_alert_name': 'Please enter alert name',
      'strategy.monitor.select_alert_type': 'Please select alert type',
      'strategy.monitor.no_error_info': 'No error information',
      'strategy.monitor.fields.strategy_name': 'Strategy Name',
      'strategy.monitor.fields.strategy_code': 'Strategy Code',
      'strategy.monitor.fields.type': 'Type',
      'strategy.monitor.fields.status': 'Status',
      'strategy.monitor.fields.priority': 'Priority',
      'strategy.monitor.fields.version': 'Version',
      'strategy.monitor.fields.description': 'Description',
      'strategy.monitor.fields.execution_count': 'Execution Count',
      'strategy.monitor.fields.success_count': 'Success Count',
      'strategy.monitor.fields.failure_count': 'Failure Count',
      'strategy.monitor.fields.last_execution_time': 'Last Execution Time',
      'strategy.monitor.fields.updated_at': 'Updated At',
      // 策略类型和状态
      'strategy.types.permission': 'Permission Strategy',
      'strategy.types.business': 'Business Strategy',
      'strategy.types.data': 'Data Strategy',
      'strategy.types.workflow': 'Workflow Strategy',
      'strategy.status.draft': 'Draft',
      'strategy.status.testing': 'Testing',
      'strategy.status.active': 'Active',
      'strategy.status.inactive': 'Inactive',
      'strategy.status.archived': 'Archived',
      // common.strategy 模块级提示信息
      'common.strategy.types.permission': 'Permission Strategy',
      'common.strategy.types.business': 'Business Strategy',
      'common.strategy.types.data': 'Data Strategy',
      'common.strategy.types.workflow': 'Workflow Strategy',
      'common.strategy.status.draft': 'Draft',
      'common.strategy.status.testing': 'Testing',
      'common.strategy.status.active': 'Active',
      'common.strategy.status.inactive': 'Inactive',
      'common.strategy.status.archived': 'Archived',
      'common.strategy.management.status_filter': 'Status Filter',
      'common.strategy.management.version_history': 'Version History',
      'common.strategy.management.version': 'Version',
      'common.strategy.management.status': 'Status',
      'common.strategy.management.updated_at': 'Updated At',
      'common.strategy.management.updated_by': 'Updated By',
      'common.strategy.management.activate': 'Activate',
      'common.strategy.management.compare': 'Compare',
      'common.strategy.management.test': 'Strategy Test',
      'common.strategy.management.test_context': 'Test Context',
      'common.strategy.management.test_context_placeholder': 'Please enter test context in JSON format',
      'common.strategy.management.test_result': 'Test Result',
      'common.strategy.management.execution_result': 'Execution Result',
      'common.strategy.management.strategy_effect': 'Strategy Effect',
      'common.strategy.management.execution_time': 'Execution Time',
      'common.strategy.management.execution_steps': 'Execution Steps',
      'common.strategy.management.success': 'Success',
      'common.strategy.management.failed': 'Failed',
      'common.strategy.management.execution_steps_detail': 'Execution Steps Detail',
      'common.strategy.management.execute_test': 'Execute Test',
      'common.strategy.management.test_complete': 'Strategy test completed',
      'common.strategy.management.test_failed': 'Strategy test failed',
      'common.strategy.management.result': 'Result',
      'common.strategy.management.error': 'Error',
      'common.strategy.management.version_activate_success': 'Version activation successful',
      'common.strategy.management.version_activate_failed': 'Version activation failed',
      'common.strategy.management.get_version_history_failed': 'Failed to get version history',
      'common.strategy.management.clone_success': 'Strategy cloned successfully',
      'common.strategy.management.clone_failed': 'Strategy clone failed',
      'common.strategy.management.copy_suffix': 'Copy',
      'common.strategy.management.export_success': 'Strategy exported successfully',
      'common.strategy.management.export_failed': 'Strategy export failed',
      'common.strategy.monitor.load_execution_history_failed': 'Failed to load execution history',
      'common.strategy.monitor.execution_replay_started': 'Execution replay started',
      'common.strategy.monitor.execution_replay_failed': 'Execution replay failed',
      'common.strategy.monitor.alert_subject': 'Strategy Monitor Alert',
      'common.strategy.monitor.please_input_alert_name': 'Please enter alert name',
      'common.strategy.monitor.please_select_alert_type': 'Please select alert type',
      'common.strategy.monitor.metrics.avg_response_time': 'Average Response Time',
      'common.strategy.monitor.metrics.p95_response_time': 'P95 Response Time',
      'common.strategy.monitor.metrics.p99_response_time': 'P99 Response Time',
      'common.strategy.monitor.metrics.error_rate': 'Error Rate',
      'common.strategy.monitor.metrics.failure_count': 'Failure Count',
      'common.strategy.monitor.metrics.execution_count': 'Execution Count',
      'common.strategy.monitor.metrics.execution_rate': 'Execution Rate',
      'common.strategy.monitor.units.times': 'times',
      'common.strategy.monitor.units.times_per_minute': 'times/min',
      'common.strategy.monitor.types.performance': 'Performance',
      'common.strategy.monitor.types.error_rate': 'Error Rate',
      'common.strategy.monitor.types.execution_count': 'Execution Count',
      'common.strategy.monitor.operators.gt': 'Greater Than',
      'common.strategy.monitor.operators.gte': 'Greater Than or Equal',
      'common.strategy.monitor.operators.lt': 'Less Than',
      'common.strategy.monitor.operators.lte': 'Less Than or Equal',
      'common.strategy.monitor.operators.eq': 'Equal',
      'common.strategy.monitor.alert_rule_preview': 'Alert Rule Preview',
      'common.strategy.monitor.alert_rule': 'Alert Rule',
      'common.strategy.monitor.please_complete_alert_config': 'Please complete alert configuration',
      'common.strategy.monitor.alert_rule_description': 'Trigger alert when {metric} {operator} {threshold}{unit} and lasts for {duration} seconds',
      'common.strategy.monitor.alert_save_success': 'Alert rule saved successfully',
      'common.strategy.monitor.delete_alert_confirm': 'Are you sure to delete this alert rule?',
      'common.strategy.monitor.alert_delete_success': 'Alert rule deleted successfully',
      'common.strategy.designer.component_library.basic': 'Basic Components',
      'common.strategy.designer.component_library.advanced': 'Advanced Components',
      'common.strategy.designer.node_types.start': 'Start',
      'common.strategy.designer.node_types.end': 'End',
      'common.strategy.designer.node_types.condition': 'Condition',
      'common.strategy.designer.node_types.action': 'Action',
      'common.strategy.designer.node_types.decision': 'Decision',
      'common.strategy.designer.node_types.gateway': 'Gateway',
      'common.strategy.designer.node_types.node': 'Node',
      'common.strategy.designer.directions.top': 'Top',
      'common.strategy.designer.directions.right': 'Right',
      'common.strategy.designer.directions.bottom': 'Bottom',
      'common.strategy.designer.directions.left': 'Left',
      'common.strategy.designer.node_management.only_one_start_node': 'Only one start node allowed in strategy',
      'common.strategy.designer.node_management.only_one_end_node': 'Only one end node allowed in strategy',
      'common.strategy.designer.node_management.delete_confirm': 'Are you sure to delete this node?',
      'common.strategy.designer.node_management.delete_success': 'Node deleted successfully',
      'common.strategy.designer.font_family.system_default': 'System Default',
      'common.strategy.designer.font_family.monospace': 'Monospace',
      'common.strategy.designer.font_family.serif': 'Serif',
      'common.strategy.designer.font_family.rounded': 'Rounded',
      'common.strategy.designer.font_family.bold': 'Bold',
      'common.strategy.designer.operations.new_orchestration': 'New Strategy Orchestration',
    },
  },

  columns: {
    'strategy.management': [
      { type: 'selection' },
      { type: 'index', label: 'common.index' },
      { prop: 'name', label: 'strategy.management.fields.strategy_name' },
      {
        prop: 'type',
        label: 'strategy.management.fields.type',
        dict: [
          { label: 'strategy.management.types.permission', value: 'PERMISSION', type: 'danger' },
          { label: 'strategy.management.types.business', value: 'BUSINESS', type: 'success' },
          { label: 'strategy.management.types.data', value: 'DATA', type: 'warning' },
          { label: 'strategy.management.types.workflow', value: 'WORKFLOW', type: 'info' }
        ],
        dictColor: true,
      },
      {
        prop: 'status',
        label: 'strategy.management.fields.status',
        dict: [
          { label: 'strategy.management.status.draft', value: 'DRAFT', type: 'info' },
          { label: 'strategy.management.status.testing', value: 'TESTING', type: 'warning' },
          { label: 'strategy.management.status.active', value: 'ACTIVE', type: 'success' },
          { label: 'strategy.management.status.inactive', value: 'INACTIVE', type: 'danger' },
          { label: 'strategy.management.status.archived', value: 'ARCHIVED', type: 'default' }
        ],
        dictColor: true,
      },
      { prop: 'priority', label: 'strategy.management.fields.priority' },
      {
        prop: 'version',
        label: 'strategy.management.fields.version',
        // 使用 slot 自定义显示
      },
      {
        prop: 'tags',
        label: 'strategy.management.fields.tags',
        // 使用 slot 自定义显示
      },
      { prop: 'description', label: 'strategy.management.fields.description' },
      { prop: 'updatedAt', label: 'strategy.management.fields.updated_at' },
    ] as TableColumn[],

    'strategy.monitor': [
      { type: 'selection' },
      { type: 'index', label: 'common.index' },
      { prop: 'name', label: 'strategy.monitor.fields.strategy_name' },
      {
        prop: 'type',
        label: 'strategy.monitor.fields.type',
        dict: [
          { label: 'strategy.management.types.permission', value: 'PERMISSION', type: 'danger' },
          { label: 'strategy.management.types.business', value: 'BUSINESS', type: 'success' },
          { label: 'strategy.management.types.data', value: 'DATA', type: 'warning' },
          { label: 'strategy.management.types.workflow', value: 'WORKFLOW', type: 'info' }
        ],
        dictColor: true,
      },
      {
        prop: 'status',
        label: 'strategy.monitor.fields.status',
        dict: [
          { label: 'strategy.management.status.draft', value: 'DRAFT', type: 'info' },
          { label: 'strategy.management.status.testing', value: 'TESTING', type: 'warning' },
          { label: 'strategy.management.status.active', value: 'ACTIVE', type: 'success' },
          { label: 'strategy.management.status.inactive', value: 'INACTIVE', type: 'danger' },
          { label: 'strategy.management.status.archived', value: 'ARCHIVED', type: 'default' }
        ],
        dictColor: true,
      },
      { prop: 'priority', label: 'strategy.monitor.fields.priority' },
      { prop: 'version', label: 'strategy.monitor.fields.version' },
      { prop: 'description', label: 'strategy.monitor.fields.description' },
      { prop: 'updatedAt', label: 'strategy.monitor.fields.updated_at' },
    ] as TableColumn[],
  },

  forms: {
    'strategy.management': [
      { prop: 'name', label: 'strategy.management.fields.strategy_name', span: 12, required: true, component: { name: 'el-input' } },
      {
        prop: 'type',
        label: 'strategy.management.fields.type',
        span: 12,
        required: true,
        component: {
          name: 'el-select',
          options: [
            { label: 'strategy.management.types.permission', value: 'PERMISSION' },
            { label: 'strategy.management.types.business', value: 'BUSINESS' },
            { label: 'strategy.management.types.data', value: 'DATA' },
            { label: 'strategy.management.types.workflow', value: 'WORKFLOW' }
          ],
        },
      },
      {
        prop: 'priority',
        label: 'strategy.management.fields.priority',
        span: 12,
        value: 100,
        component: {
          name: 'el-input-number',
          props: { min: 0, max: 1000 },
        },
      },
      {
        prop: 'tags',
        label: 'strategy.management.fields.tags',
        span: 12,
        component: {
          name: 'el-input',
          props: { placeholder: 'strategy.management.tags_placeholder' },
        },
      },
      {
        prop: 'status',
        label: 'strategy.management.fields.status',
        span: 12,
        component: {
          name: 'el-select',
          options: [
            { label: 'strategy.management.status.draft', value: 'DRAFT' },
            { label: 'strategy.management.status.testing', value: 'TESTING' },
            { label: 'strategy.management.status.active', value: 'ACTIVE' },
            { label: 'strategy.management.status.inactive', value: 'INACTIVE' },
            { label: 'strategy.management.status.archived', value: 'ARCHIVED' },
          ],
        },
      },
      { prop: 'description', label: 'strategy.management.fields.description', span: 24, component: { name: 'el-input', props: { type: 'textarea', rows: 3 } } },
    ] as FormItem[],
  },

  get service() {
    const epsService = getService();
    return {
      strategy: epsService.admin?.strategy,
    };
  },
} satisfies ModuleConfig;
