#!/usr/bin/env bash
#===============================================================================
# PR 提交脚本
# 功能：审核通过后自动提交 PR，触发 CI/CD
# 用法：
#   ./pr-submitter.sh submit <project> <milestone>       # 提交 PR
#   ./pr-submitter.sh check                             # 检查 CI/CD 状态
#   ./pr-submitter.sh template <project> <milestone>     # 生成 PR 模板
#   ./pr-submitter.sh prepare <project> <milestone>      # 准备提交
#===============================================================================

set -euo pipefail

# 配置
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STATE_DIR="${STATE_DIR:-$HOME/.claude/state}"

# Git 配置
BRANCH="${GIT_BRANCH:-$(git branch --show-current 2>/dev/null || echo 'develop')}"
REMOTE="${GIT_REMOTE:-origin}"

# 颜色输出
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

#-------------------------------------------------------------------------------
# 检查 Git 状态
#-------------------------------------------------------------------------------
check_git_status() {
    log_info "检查 Git 状态..."

    # 检查是否有未提交的更改
    if [[ -n "$(git status --porcelain 2>/dev/null)" ]]; then
        log_warn "存在未提交的更改"
        git status --short
        return 1
    fi

    # 检查当前分支
    log_info "当前分支: $BRANCH"

    # 检查远程分支是否存在
    if git ls-remote --heads "$REMOTE" "$BRANCH" &>/dev/null; then
        log_info "远程分支 $REMOTE/$BRANCH 存在"
    else
        log_warn "远程分支 $REMOTE/$BRANCH 不存在，将创建"
    fi

    return 0
}

#-------------------------------------------------------------------------------
# 同步远程分支
#-------------------------------------------------------------------------------
sync_remote() {
    log_info "同步远程分支..."

    # 获取最新代码
    git fetch "$REMOTE" 2>/dev/null || log_warn "无法获取远程更新"

    # 检查本地分支是否落后
    local local_commit remote_commit base_commit
    local_commit=$(git rev-parse HEAD 2>/dev/null)
    remote_commit=$(git rev-parse "$REMOTE/$BRANCH" 2>/dev/null || echo "")

    if [[ -n "$remote_commit" ]]; then
        local common_base
        common_base=$(git merge-base "$local_commit" "$remote_commit" 2>/dev/null || echo "")

        if [[ "$local_commit" == "$remote_commit" ]]; then
            log_success "本地分支已是最新"
        elif [[ "$common_base" == "$remote_commit" ]]; then
            log_warn "本地分支领先远程"
            log_info "建议: git push $REMOTE $BRANCH"
        else
            log_warn "本地分支与远程有分歧"
            log_info "建议: git pull 或 git push --force"
        fi
    fi
}

#-------------------------------------------------------------------------------
# 提交更改
#-------------------------------------------------------------------------------
commit_changes() {
    local project="${1:-}"
    local milestone="${2:-}"

    log_info "提交更改..."

    # 检查是否有更改需要提交
    if [[ -z "$(git status --porcelain 2>/dev/null)" ]]; then
        log_warn "没有需要提交的更改"
        return 1
    fi

    # 暂存所有更改
    git add -A

    # 生成提交消息
    local commit_message
    local date
    date=$(date +%Y-%m-%d)

    if [[ -n "$project" ]] && [[ -n "$milestone" ]]; then
        commit_message="feat($project): 完成 $milestone 里程碑

- 完成了所有原子任务
- 通过了 Reviewer 全局校验
- 符合 CI/CD 质量标准

Generated by Claude Code PR Submitter"
    else
        commit_message="chore: 代码更新 - $date

Generated by Claude Code PR Submitter"
    fi

    # 提交
    if git commit -m "$commit_message"; then
        log_success "提交成功"
        git log -1 --oneline
    else
        log_error "提交失败"
        return 1
    fi
}

#-------------------------------------------------------------------------------
# 推送到远程
#-------------------------------------------------------------------------------
push_remote() {
    log_info "推送到远程 $REMOTE..."

    # 检查是否有上游分支设置
    local upstream
    upstream=$(git upstream 2>/dev/null || git branch --set-upstream-to="$REMOTE/$BRANCH" "$BRANCH" 2>/dev/null || echo "")

    if git push "$REMOTE" "$BRANCH"; then
        log_success "推送成功到 $REMOTE/$BRANCH"
        return 0
    else
        log_error "推送失败"
        return 1
    fi
}

#-------------------------------------------------------------------------------
# 创建 PR
#-------------------------------------------------------------------------------
create_pr() {
    local project="${1:-}"
    local milestone="${2:-}"

    log_info "检查是否需要创建 PR..."

    # 检查当前分支
    local base_branch="develop"
    if [[ "$BRANCH" == "main" ]] || [[ "$BRANCH" == "master" ]]; then
        log_warn "当前在主分支，无需创建 PR"
        return 0
    fi

    # 检查是否已有同名 PR
    if command -v gh &> /dev/null; then
        local existing_pr
        existing_pr=$(gh pr list --head "$BRANCH" --state all 2>/dev/null | grep -c "$BRANCH" || echo "0")

        if [[ "$existing_pr" -gt 0 ]]; then
            log_warn "已存在 $existing_pr 个同名 PR"
            return 1
        fi
    fi

    # 生成 PR 标题
    local pr_title
    local pr_body

    if [[ -n "$project" ]] && [[ -n "$milestone" ]]; then
        pr_title="feat($project): 完成 $milestone 里程碑"
        pr_body=$(generate_pr_body "$project" "$milestone")
    else
        pr_title="feat: 代码更新 $(date +%Y-%m-%d)"
        pr_body=$(generate_pr_body)
    fi

    echo ""
    log_info "PR 标题: $pr_title"
    echo ""

    # 如果有 gh CLI，创建 PR
    if command -v gh &> /dev/null; then
        log_info "使用 GitHub CLI 创建 PR..."

        if gh pr create --title "$pr_title" --body "$pr_body" --base "$base_branch" --head "$BRANCH"; then
            log_success "PR 创建成功"
            return 0
        else
            log_warn "PR 创建失败（可能需要手动创建）"
            echo ""
            echo "请手动创建 PR:"
            echo "  标题: $pr_title"
            echo "  源分支: $BRANCH"
            echo "  目标分支: $base_branch"
        fi
    else
        log_warn "GitHub CLI 未安装，请手动创建 PR"
    fi

    # 保存 PR 模板供手动使用
    local pr_template_file="PULL_REQUEST_TEMPLATE.md"
    cat > "$pr_template_file" <<EOF
# $pr_title

$pr_body

---

## 检查清单

- [ ] 所有 Worker 任务完成
- [ ] Reviewer 校验通过
- [ ] CI/CD 测试通过
- [ ] 代码审查通过

## 关联任务

<!-- 链接到相关任务 -->
EOF

    log_info "PR 模板已保存: $pr_template_file"
    return 1
}

#-------------------------------------------------------------------------------
# 生成 PR 内容
#-------------------------------------------------------------------------------
generate_pr_body() {
    local project="${1:-}"
    local milestone="${2:-}"

    cat <<EOF
## 概述

本 PR 完成了以下工作：

<!-- 描述主要变更 -->

## 变更内容

### 新增功能
-

### 修复问题
-

### 代码优化
-

## 测试

- [ ] 单元测试通过
- [ ] E2E 测试通过
- [ ] 手动测试通过

## 检查清单

- [ ] 代码符合项目规范
- [ ] 无新的 lint 错误
- [ ] 构建成功
- [ ] 类型检查通过
EOF

    if [[ -n "$project" ]] && [[ -n "$milestone" ]]; then
        cat <<EOF

## 关联里程碑

- 项目: $project
- 里程碑: $milestone
EOF
    fi
}

#-------------------------------------------------------------------------------
# 检查 CI/CD 状态
#-------------------------------------------------------------------------------
check_cicd() {
    log_info "检查 CI/CD 状态..."

    # 检查 GitHub Actions（如果有 gh CLI）
    if command -v gh &> /dev/null; then
        local runs
        runs=$(gh run list --limit 5 2>/dev/null || echo "无法获取工作流运行记录")

        echo "$runs"
        return 0
    fi

    # 检查本地 CI 配置
    if [[ -f ".github/workflows/ci.yml" ]]; then
        log_info "GitHub Actions CI 配置存在"
    fi

    if [[ -f ".gitlab-ci.yml" ]]; then
        log_info "GitLab CI 配置存在"
    fi

    if [[ -f "Jenkinsfile" ]]; then
        log_info "Jenkins CI 配置存在"
    fi

    return 0
}

#-------------------------------------------------------------------------------
# 触发 CI/CD
#-------------------------------------------------------------------------------
trigger_cicd() {
    log_info "触发 CI/CD..."

    # 通过推送触发 GitHub Actions
    if git push "$REMOTE" "$BRANCH" 2>/dev/null; then
        log_success "CI/CD 已触发（通过推送）"

        # 等待并检查状态
        sleep 5
        check_cicd
    else
        log_error "触发 CI/CD 失败"
    fi
}

#-------------------------------------------------------------------------------
# 准备提交（综合命令）
#-------------------------------------------------------------------------------
cmd_prepare() {
    local project="${1:-}"
    local milestone="${2:-}"

    echo ""
    echo -e "${CYAN}═══════════════════════════════════════${NC}"
    echo -e "${CYAN}     准备 PR 提交${NC}"
    echo -e "${CYAN}═══════════════════════════════════════${NC}"
    echo ""

    # 1. 检查 Git 状态
    check_git_status || true

    # 2. 同步远程
    sync_remote

    # 3. 提交更改
    if [[ -n "$(git status --porcelain 2>/dev/null)" ]]; then
        commit_changes "$project" "$milestone"
    else
        log_info "无需要提交的更改"
    fi

    # 4. 推送到远程
    push_remote

    log_success "准备完成，可以创建 PR"
}

#-------------------------------------------------------------------------------
# 提交 PR
#-------------------------------------------------------------------------------
cmd_submit() {
    local project="${1:-}"
    local milestone="${2:-}"

    echo ""
    echo -e "${CYAN}═══════════════════════════════════════${NC}"
    echo -e "${CYAN}     提交 PR${NC}"
    echo -e "${CYAN}═══════════════════════════════════════${NC}"
    echo ""

    # 检查 Reviewer 是否通过
    local review_status="unknown"
    if [[ -n "$project" ]]; then
        local review_file="$STATE_DIR/projects/$project/milestones/${milestone:-default}/review.json"
        if [[ -f "$review_file" ]]; then
            review_status=$(grep -oP '"status":\s*"\K[^"]+' "$review_file" 2>/dev/null || echo "unknown")
            log_info "Reviewer 状态: $review_status"

            if [[ "$review_status" != "approved" ]]; then
                log_warn "Reviewer 尚未通过，请先完成审核"
                return 1
            fi
        fi
    fi

    # 1. 准备提交
    cmd_prepare "$project" "$milestone"

    # 2. 创建 PR
    create_pr "$project" "$milestone"

    # 3. 触发 CI/CD
    echo ""
    log_info "触发 CI/CD..."
    trigger_cicd

    # 4. 保存提交记录
    save_submission "$project" "$milestone"

    echo ""
    log_success "PR 提交流程完成"
}

#-------------------------------------------------------------------------------
# 保存提交记录
#-------------------------------------------------------------------------------
save_submission() {
    local project="${1:-}"
    local milestone="${2:-}"

    local submission_dir="$STATE_DIR/submissions/$project/$milestone"
    mkdir -p "$submission_dir"

    local commit_hash
    commit_hash=$(git rev-parse HEAD 2>/dev/null || echo "unknown")

    cat > "$submission_dir/submission.json" <<EOF
{
  "project": "$project",
  "milestone": "$milestone",
  "branch": "$BRANCH",
  "commit_hash": "$commit_hash",
  "submitted_at": "$(date -Iseconds)",
  "ci_cd_triggered": true,
  "pr_created": true
}
EOF

    log_success "提交记录已保存: $submission_dir/submission.json"
}

#-------------------------------------------------------------------------------
# 生成 PR 模板
#-------------------------------------------------------------------------------
cmd_template() {
    local project="${1:-}"
    local milestone="${2:-}"

    local template_file="docs/pull-requests/PROJECT-$(echo $project | tr '[:lower:]' '[:upper:]')-$milestone.md"
    mkdir -p "$(dirname "$template_file")"

    cat > "$template_file" <<EOF
---
name: 项目功能 PR
about: 描述这个 PR 解决的问题

---

## 关联里程碑

- 项目: $project
- 里程碑: $milestone

## 功能描述

<!-- 描述这个 PR 添加或修复的功能 -->

## 变更类型

- [ ] 新功能 (feat)
- [ ] 修复bug (fix)
- [ ] 文档更新 (docs)
- [ ] 代码格式 (style)
- [ ] 代码重构 (refactor)
- [ ] 测试 (test)
- [ ] 其他 (chore)

## 测试清单

- [ ] 单元测试通过
- [ ] 集成测试通过
- [ ] E2E 测试通过（如适用）
- [ ] 手动测试通过

## 检查清单

- [ ] 代码符合项目的编码规范
- [ ] 新增的 API 有文档
- [ ] 变量命名清晰
- [ ] 无硬编码的敏感信息
- [ ] 构建成功
- [ ] 类型检查通过

## 相关 Issue

<!-- 链接到相关的 Issue -->
EOF

    log_success "PR 模板已生成: $template_file"
}

#-------------------------------------------------------------------------------
# 初始化 PR 相关目录
#-------------------------------------------------------------------------------
init_pr_dirs() {
    log_info "初始化 PR 目录结构..."

    mkdir -p "docs/pull-requests"
    mkdir -p "docs/changelogs"

    # 创建 .gitmessage 模板
    cat > ".gitmessage" <<EOF
# 类型(<模块>): 简要描述

# 为什么需要这个变更

# 变更内容

# 测试结果

# 相关链接

---
Generated by Claude Code PR Submitter
EOF

    log_success "PR 目录初始化完成"
}

#-------------------------------------------------------------------------------
# 主入口
#-------------------------------------------------------------------------------
main() {
    local command="${1:-help}"

    case "$command" in
        submit|s)
            shift
            cmd_submit "$@"
            ;;
        prepare|pre)
            shift
            cmd_prepare "$@"
            ;;
        check|c)
            check_cicd
            ;;
        trigger|t)
            trigger_cicd
            ;;
        template|tpl)
            shift
            cmd_template "$@"
            ;;
        init|i)
            init_pr_dirs
            ;;
        help|--help|-h)
            echo "PR 提交脚本 - CI/CD 自动化"
            echo ""
            echo "用法: $0 <命令> [参数]"
            echo ""
            echo "命令:"
            echo "  submit <project> <milestone>  完整提交流程（审核 → 提交 → PR → CI/CD）"
            echo "  prepare <project> <milestone> 准备提交（检查 → 同步 → 提交 → 推送）"
            echo "  check                       检查 CI/CD 状态"
            echo "  trigger                     触发 CI/CD"
            echo "  template <project> <milestone> 生成 PR 模板"
            echo "  init                        初始化 PR 相关目录"
            echo "  help                        显示帮助"
            echo ""
            echo "示例:"
            echo "  $0 submit DesignToken v1.0"
            echo "  $0 prepare DesignToken v1.0"
            echo "  $0 template DesignToken v1.0"
            echo ""
            echo "工作流程:"
            echo "  1. Reviewer 审核通过"
            echo "  2. 执行 submit 脚本"
            echo "  3. 脚本自动提交代码"
            echo "  4. 创建 PR"
            echo "  5. 触发 CI/CD"
            echo ""
            ;;
        *)
            log_error "未知命令: $command"
            $0 help
            exit 1
            ;;
    esac
}

main "$@"
